version: '2.1'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${EMBED_API_MONGO_USER:-MONGOUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${EMBED_API_MONGO_PASS:-MONGOPASS}
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
  embed-api:
    build: .
    ports:
      - "3050:3050"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      EMBED_API_HOST: ${EMBED_API_HOST:-0.0.0.0}
      EMBED_API_PORT: 3050
      EMBED_API_TOKEN: ${EMBED_API_TOKEN:-embedapitoken}
      EMBED_API_MONGO_DB: mongodb://${EMBED_API_MONGO_USER:-MONGOUSER}:${EMBED_API_MONGO_PASS:-MONGOPASS}@mongodb:27017/embed_api?authSource=admin
